apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: java-quarkus-167645952
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: java-quarkus-167645952
    app.kubernetes.io/part-of: test-app-167645945
  name: java-quarkus-167645952
  namespace: skhileri-tenant
spec:
  replicas: 1
  selector:
    matchLabels:
      app: java-quarkus-app
      app.kubernetes.io/instance: java-quarkus-167645952
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: java-quarkus-app
        app.kubernetes.io/instance: java-quarkus-167645952
    spec:
      containers:
      - image: quay.io/redhat-appstudio/user-workload@sha256:fe812318c9e8b711c668c40ce7d8a220be373b8e8b6f1068f87041fdc9de33b8
        name: my-java-quarkus
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 100m
            memory: 250Mi
          requests:
            cpu: 10m
            memory: 100Mi
status: {}
